apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-cacher-ng
  namespace: cyclops-assets
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: apt-cacher-ng
  template:
    metadata:
      labels:
        app: apt-cacher-ng
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cyclops-k8s.io/ansible-kubernetes
                operator: In
                values:
                - amd64
      containers:
      - name: apt-cacher-ng
        image: quay.io/cyclops-k8s/apt-cacher-ng:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /style.css
            port: 3142
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 3142
          name: http
        volumeMounts:
        - mountPath: /var/cache/apt-cacher-ng
          name: apt-cacher-ng-cache
      securityContext:
        fsGroup: 101
      volumes:
      - name: apt-cacher-ng-cache
        persistentVolumeClaim:
          claimName: apt-cacher-ng-cache
