apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: assets-cyclops
  namespace: cyclops-assets
spec:
  commonName: assets.cyclops-assets
  dnsNames:
  - assets.cyclops-assets
  - assets
  - localhost
  duration: 720h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: certificate-authority
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  renewBefore: 480h0m0s
  secretName: assets-cyclops-tls
  subject:
    organizations:
    - Cyclops-k8s
  usages:
  - server auth
  - client auth
