apiVersion: v1
kind: ConfigMap
metadata:
  name: assets
  namespace: cyclops-assets
data:
  default.conf: |
    server {
        listen              80;
        listen              443 ssl;
        server_name         assets.cyclops-assets;
        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location = /healthz {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "healthy\n";
        }

        location / {
            root   /usr/share/nginx/html;
        }
    }
