apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: cyclops-assets
  namespace: cyclops-assets
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cyclops-assets
  template:
    metadata:
      labels:
        app: cyclops-assets
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cyclops-k8s.io/ansible-kubernetes
                operator: In
                values:
                - amd64
      containers:
      - name: cyclops-assets
        image: nginx:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        resources:
          limits:
            cpu: 1500m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: assets
        - mountPath: /etc/nginx/conf.d
          name: assets-cm
        - mountPath: /etc/nginx/ssl
          name: ssl-certs
        - mountPath: /usr/share/nginx/html/.well-known
          name: well-known
        - mountPath: /usr/share/nginx/html/ssl-ca
          name: ssl-certs-ca
      volumes:
      - name: assets
        persistentVolumeClaim:
          claimName: assets
      - name: assets-cm
        configMap:
          name: assets
      - name: ssl-certs
        secret:
          secretName: assets-cyclops-tls
      - name: ssl-certs-ca
        secret:
          items:
          - key: ca.crt
            path: ca.crt
          secretName: assets-cyclops-tls
      - name: well-known
        configMap:
          defaultMode: 420
          name: well-known
