apiVersion: v1
kind: Service
metadata:
  name: mirror-registry-k8s-io
  namespace: cyclops-assets
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: mirror-registry-k8s-io
  trafficDistribution: PreferSameNode
