apiVersion: v1
kind: Service
metadata:
  name: mirror-quay-io
  namespace: cyclops-assets
spec:
  selector:
    app: mirror-quay-io
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
  trafficDistribution: PreferSameNode
