apiVersion: v1
kind: Service
metadata:
  name: mirror-docker-io
  namespace: cyclops-assets
spec:
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
  selector:
    app: mirror-docker-io
  trafficDistribution: PreferSameNode
