apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mirror-quay-io
  namespace: cyclops-assets
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mirror-quay-io
  template:
    metadata:
      labels:
        app: mirror-quay-io
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cyclops-k8s.io/ansible-kubernetes
                operator: In
                values:
                - amd64
      automountServiceAccountToken: false
      containers:
      - name: mirror
        image: registry:3
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1000m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-storage
        - mountPath: /etc/distribution
          name: registry-config
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: mirror-quay-io
      - name: registry-config
        configMap:
          name: mirror-quay-io
