apiVersion: batch/v1
kind: CronJob
metadata:
  name: os-image-sync
  namespace: cyclops-assets
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          containers:
          - name: image-sync
            command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /assets/os-images/new
              apt update && apt install -y curl
              cd /assets/os-images/new
              # Download desired OS assets/os-images
              for url in $(echo "$urls"); do
                echo "Downloading $url"
                curl -O "$url"
              done
              mv /assets/os-images/new/* /assets/os-images/
            envFrom:
            - configMapRef:
                name: os-images
            image: ubuntu:latest
            volumeMounts:
            - mountPath: /assets
              name: assets
          restartPolicy: Never
          volumes:
          - name: assets
            persistentVolumeClaim:
              claimName: assets
  schedule: "0 0 * * *"
