apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: registry-mirrors
  namespace: cyclops-assets
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: registry-mirrors
  template:
    metadata:
      labels:
        app: registry-mirrors
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cyclops-k8s.io/ansible-kubernetes
                operator: In
                values:
                - amd64
      automountServiceAccountToken: false
      containers:
      - name: proxy
        image: nginx:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: sites
        - mountPath: /etc/nginx/ssl
          name: ssl-certs
        resources:
          limits:
            cpu: 1500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 50Mi
      volumes:
      - name: sites
        configMap:
          name: registry-mirrors-proxy
      - name: ssl-certs
        secret:
          secretName: registry-mirrors-cyclops-tls
